version: '3.3'
services:
  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  productService:
    image: productimage
    build: ProductByMongo/
    restart: always
    hostname: localhost
    network_mode: host
    depends_on:
      - mongo
      - eurekaserver
      - cloudapiservice
    ports:
      - 8086:8086
  mongo:
    image: mongo:3.2-jessie
    ports:
      - 27017:27017
    container_name: mongo
    network_mode: host

  authenticationservice:
    container_name: user-authentication-service
    build: authenticationService/
    hostname: localhost
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice
      - eurekaserver
      - cloudapiservice
    restart: always

  cloudapiservice:
    image: cloude-api-service
    build: Microservice_API_Gateway/
    restart: always
    network_mode: host
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eurekaserver

  eurekaserver:
    image: eureka-service
    build: NetflixEurekaServer/
    restart: always
    network_mode: host
    environment:
      EUREKA_SERVER_PORT: 8761
    ports:
      - 8761:8761







